spring:
  application:
    name: api-core-java
  profiles:
    active: dev        

---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:postgresql://${DB_HOST:db}:${DB_PORT:5432}/${DB_NAME:writeflow}
    username: ${DB_USER:writeflow}
    password: ${DB_PASSWORD:writeflow}
  jpa:
    hibernate:
      ddl-auto: update          
    properties:
      hibernate:
        format_sql: true        

---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:postgresql://${DB_HOST:db}:${DB_PORT:5432}/${DB_NAME:writeflow}
    username: ${DB_USER:writeflow}
    password: ${DB_PASSWORD:writeflow}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc.lob.non_contextual_creation: true
        format_sql: true

jwt:
  secret: ${JWT_SECRET:vwpisbdEF8#&dbeDI23}

server:
  port: ${PORT:8081}
